archive:
  name_template: "core_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  format: zip
builds:
  - main: main.go
    binary: core
    goos:
      - windows
      - darwin
      - linux
    env:
      - ENV=production
