[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/akamensky/argparse"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"
